### ISSUE TITLE
Thoughts on Sequin?

### ISSUE THREAD

**Issue by thisisgoldman** [pachacamac/pachacamac#3]
Hey Marc,

I'm one of the developers working on Sequin (https://github.com/sequinstream/sequin). I saw you come through as one of our first 100 stars - thank you!

I saw you might have worked with Supabase (at least you follow their repo :)

We're thinking about making Sequin work better with Supabase so that it's easy to add an SQS / Kafka-like message stream to existing tables.

We want to steer the project in a valuable direction. Curious if that's interesting to you given your work with Supabase?

What do you think?

Eric

**Comment by pachacamac** [comment]
Hey Eric,

Thanks for reaching out and for working on this. I contacted you on LinkedIn.

Cheers
