### ISSUE TITLE
Thanks for starring iso20022! 

### ISSUE THREAD

**Issue by svapnil-woodsidelabs** [pachacamac/pachacamac#4]
Hey Marc,

Thanks for starring the iso20022 repo - I wanted to learn more about why you were interested in it, and I'd love to hear more about it from you. I saw you were based in Germany, and I think it would be really cool to add SEPA payments to this one day

If you had the time, I'd really love to meet and hear from you - if you can, I'd love if you could email me at svapnil@woodside.sh / or maybe even find a time to us to meet cal.com/woodside/30min just to chat.

**Comment by pachacamac** [comment]
contacted you via email
